In [2]:
from yahoo_finance_api2 import share
from yahoo_finance_api2.exceptions import YahooFinanceError
import pandas as pd
import datetime
import os
import time

In [6]:
gyousyu_list=[ "水産・農林 ","鉱業","建設","食料品","繊維製品","パルプ・紙","化学","医薬品","石油・石炭","ゴム製品","硝子・土石","鉄鋼","非鉄金属","金属製品","機械","電気機器","輸送機器","精密機器","その他製造","電気・ガス","陸運","海運","空運","倉庫・運輸","情報・通信","卸売","小売","銀行","証券・商品","保険","その他金融","不動産","サービス"]

In [17]:
def get_data(data_dict):
    now = datetime.datetime.now()
    now = now.strftime("%y%m%d")
    num = len(data_dict)

    legend_list = []
    i = 0
    for mykey, company_name in data_dict.items():
        company_code = str(mykey) + '.T'
        my_share = share.Share(company_code)
        time.sleep(5)
        
        try:
            symbol_data = my_share.get_historical(share.PERIOD_TYPE_DAY, 120,
                                                      share.FREQUENCY_TYPE_MINUTE, 5)

            df = pd.DataFrame(symbol_data.values(), index=symbol_data.keys()).T
            df.timestamp = pd.to_datetime(df.timestamp, unit='ms')
            # 日本標準時間に変換
            df.index = pd.DatetimeIndex(df.timestamp, name='timestamp').tz_localize('UTC').tz_convert('Asia/Tokyo')
            # csvファイルに保存
            df.to_csv(now + "_" + str(mykey) + "_" + company_name + ".csv", index=False)
            print(f'{mykey} complete')

        except YahooFinanceError as e:
            print(f'{e.message},{mykey},{company_name}')
            pass
        i += 1

In [4]:
os.getcwd()

'C:\\Users\\track\\Desktop\\Machine Learning\\株価予測\\stock_data\\小売'

In [5]:
#os.chdir('./小売')
f = open("dict_小売.txt",  'r')
data = f.read()
data = data.split(" ")
del data[-1]
dict_data={}
for i in range(0,len(data),2):
    dict_data[data[i]]=data[i+1]

In [8]:
dict_data={'2651':'ローソン'}

In [9]:
os.chdir('./小売')

In [19]:
del dict_data["2651"]

In [24]:
for i in range(2651,3198):
    try:
        del dict_data[str(i)]
    except KeyError:
        continue

In [18]:
get_data(dict_data)

2651 complete

In [5]:
company_code = '2651.T'
my_share = share.Share(company_code)
symbol_data = my_share.get_historical(share.PERIOD_TYPE_DAY, 1,share.FREQUENCY_TYPE_MINUTE, 5)
df = pd.DataFrame(symbol_data.values(), index=symbol_data.keys()).T
df.timestamp = pd.to_datetime(df.timestamp, unit='ms')
df.index = pd.DatetimeIndex(df.timestamp, name='timestamp').tz_localize('UTC').tz_convert('Asia/Tokyo')
df

,timestamp,open,high,low,close,volume
timestamp,,,,,,
2022-06-16 12:30:00+09:00,2022-06-16 03:30:00,4305.0,4315.0,4305.0,4310.0,0.0
2022-06-16 12:35:00+09:00,2022-06-16 03:35:00,4305.0,4310.0,4295.0,4295.0,14800.0
2022-06-16 12:40:00+09:00,2022-06-16 03:40:00,4295.0,4305.0,4290.0,4290.0,8400.0
2022-06-16 12:45:00+09:00,2022-06-16 03:45:00,4295.0,4295.0,4290.0,4290.0,1800.0
2022-06-16 12:50:00+09:00,2022-06-16 03:50:00,4295.0,4295.0,4290.0,4295.0,2000.0
...,...,...,...,...,...,...
2022-06-17 11:20:00+09:00,2022-06-17 02:20:00,4285.0,4290.0,4280.0,4285.0,5800.0
2022-06-17 11:25:00+09:00,2022-06-17 02:25:00,4285.0,4290.0,4285.0,4290.0,5100.0
2022-06-17 11:30:00+09:00,2022-06-17 02:30:00,4290.0,4290.0,4290.0,4290.0,200.0
2022-06-17 11:35:00+09:00,2022-06-17 02:35:00,NaN,NaN,NaN,NaN,NaN
2022-06-17 11:35:01+09:00,2022-06-17 02:35:01,4290.0,4290.0,4290.0,4290.0,0.0

In [7]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df

,timestamp,open,high,low,close,volume
timestamp,,,,,,
2022-06-16 12:30:00+09:00,2022-06-16 03:30:00,4305.0,4315.0,4305.0,4310.0,0.0
2022-06-16 12:35:00+09:00,2022-06-16 03:35:00,4305.0,4310.0,4295.0,4295.0,14800.0
2022-06-16 12:40:00+09:00,2022-06-16 03:40:00,4295.0,4305.0,4290.0,4290.0,8400.0
2022-06-16 12:45:00+09:00,2022-06-16 03:45:00,4295.0,4295.0,4290.0,4290.0,1800.0
2022-06-16 12:50:00+09:00,2022-06-16 03:50:00,4295.0,4295.0,4290.0,4295.0,2000.0
2022-06-16 12:55:00+09:00,2022-06-16 03:55:00,4295.0,4295.0,4295.0,4295.0,6200.0
2022-06-16 13:00:00+09:00,2022-06-16 04:00:00,4295.0,4295.0,4295.0,4295.0,2200.0
2022-06-16 13:05:00+09:00,2022-06-16 04:05:00,4300.0,4300.0,4295.0,4300.0,1700.0
2022-06-16 13:10:00+09:00,2022-06-16 04:10:00,4300.0,4310.0,4300.0,4310.0,35700.0
2022-06-16 13:15:00+09:00,2022-06-16 04:15:00,4310.0,4310.0,4310.0,4310.0,5900.0
2022-06-16 13:20:00+09:00,2022-06-16 04:20:00,4305.0,4305.0,4305.0,4305.0,100.0
2022-06-16 13:25:00+09:00,2022-06-16 04:25:00,4310.0,4310.0,4310.0,4310.0,200.0
2022-06-16 13:30:00+09:00,2022-06-16 04:30:00,4310.0,4310.0,4310.0,4310.0,600.0
2022-06-16 13:35:00+09:00,2022-06-16 04:35:00,4310.0,4315.0,4310.0,4315.0,4000.0
2022-06-16 13:40:00+09:00,2022-06-16 04:40:00,4315.0,4315.0,4310.0,4310.0,8100.0
2022-06-16 13:45:00+09:00,2022-06-16 04:45:00,4305.0,4305.0,4305.0,4305.0,900.0
2022-06-16 13:50:00+09:00,2022-06-16 04:50:00,4305.0,4305.0,4295.0,4295.0,21100.0
2022-06-16 13:55:00+09:00,2022-06-16 04:55:00,4295.0,4295.0,4295.0,4295.0,6000.0
2022-06-16 14:00:00+09:00,2022-06-16 05:00:00,4290.0,4290.0,4285.0,4290.0,9800.0
2022-06-16 14:05:00+09:00,2022-06-16 05:05:00,4285.0,4290.0,4285.0,4285.0,500.0
2022-06-16 14:10:00+09:00,2022-06-16 05:10:00,4285.0,4285.0,4275.0,4275.0,8500.0
2022-06-16 14:15:00+09:00,2022-06-16 05:15:00,4280.0,4280.0,4275.0,4275.0,8900.0
2022-06-16 14:20:00+09:00,2022-06-16 05:20:00,4280.0,4280.0,4275.0,4275.0,5500.0
2022-06-16 14:25:00+09:00,2022-06-16 05:25:00,4280.0,4280.0,4280.0,4280.0,2500.0
2022-06-16 14:30:00+09:00,2022-06-16 05:30:00,4285.0,4285.0,4275.0,4275.0,12200.0
2022-06-16 14:35:00+09:00,2022-06-16 05:35:00,4275.0,4275.0,4275.0,4275.0,400.0
2022-06-16 14:40:00+09:00,2022-06-16 05:40:00,4280.0,4280.0,4280.0,4280.0,1000.0
2022-06-16 14:45:00+09:00,2022-06-16 05:45:00,4280.0,4280.0,4275.0,4280.0,1100.0
2022-06-16 14:50:00+09:00,2022-06-16 05:50:00,4280.0,4280.0,4275.0,4280.0,2800.0
2022-06-16 14:55:00+09:00,2022-06-16 05:55:00,4280.0,4285.0,4275.0,4280.0,15900.0
2022-06-17 09:00:00+09:00,2022-06-17 00:00:00,4230.0,4255.0,4210.0,4220.0,17900.0
2022-06-17 09:05:00+09:00,2022-06-17 00:05:00,4225.0,4230.0,4215.0,4220.0,7900.0
2022-06-17 09:10:00+09:00,2022-06-17 00:10:00,4220.0,4235.0,4220.0,4230.0,10300.0
2022-06-17 09:15:00+09:00,2022-06-17 00:15:00,4225.0,4240.0,4225.0,4235.0,21500.0
2022-06-17 09:20:00+09:00,2022-06-17 00:20:00,4235.0,4245.0,4230.0,4240.0,12600.0
2022-06-17 09:25:00+09:00,2022-06-17 00:25:00,4245.0,4255.0,4240.0,4245.0,16300.0
2022-06-17 09:30:00+09:00,2022-06-17 00:30:00,4245.0,4260.0,4245.0,4255.0,11500.0
2022-06-17 09:35:00+09:00,2022-06-17 00:35:00,4255.0,4270.0,4255.0,4265.0,10600.0
2022-06-17 09:40:00+09:00,2022-06-17 00:40:00,4265.0,4265.0,4245.0,4250.0,13900.0
2022-06-17 09:45:00+09:00,2022-06-17 00:45:00,4250.0,4265.0,4250.0,4265.0,6400.0
2022-06-17 09:50:00+09:00,2022-06-17 00:50:00,4265.0,4275.0,4260.0,4265.0,10800.0
2022-06-17 09:55:00+09:00,2022-06-17 00:55:00,4265.0,4265.0,4260.0,4265.0,6200.0
2022-06-17 10:00:00+09:00,2022-06-17 01:00:00,4270.0,4275.0,4265.0,4270.0,12000.0
2022-06-17 10:05:00+09:00,2022-06-17 01:05:00,4275.0,4275.0,4275.0,4275.0,6900.0
2022-06-17 10:10:00+09:00,2022-06-17 01:10:00,4280.0,4280.0,4275.0,4275.0,4900.0
2022-06-17 10:15:00+09:00,2022-06-17 01:15:00,4280.0,4285.0,4280.0,4285.0,2000.0
2022-06-17 10:20:00+09:00,2022-06-17 01:20:00,4285.0,4285.0,4280.0,4280.0,10100.0
2022-06-17 10:25:00+09:00,2022-06-17 01:25:00,4280.0,4280.0,4275.0,4275.0,7800.0
2022-06-17 10:30:00+09:00,2022-06-17 01:30:00,4275.0,4275.0,4275.0,4275.0,2900.0
2022-06-17 10:35:00+09:00,2022-06-17 01:35:00,4275.0,4275.0,4270.0,4275.0,6300.0
2022-06-17 10:40:00+09:00,2022-06-17 01:40:00,4275.0,4280.0,4270.0,4280.0,6500.0
2022-06-17 10:45:00+09:00,2022-06-17 01:45:00,4280.0,4280.0,4280.0,4280.0,7100.0
2022-06-17 10:50:00+09:00,2022-06-17 01:50:00,4285.0,4295.0,4285.0,4290.0,12200.0
2022-06-17 10:55:00+09:00,2022-06-17 01:55:00,4290.0,4290.0,4285.0,4290.0,3800.0
2022-06-17 11:00:00+09:00,2022-06-17 02:00:00,4290.0,4290.0,4280.0,4285.0,5400.0
2022-06-17 11:05:00+09:00,2022-06-17 02:05:00,4280.0,4280.0,4280.0,4280.0,4500.0
2022-06-17 11:10:00+09:00,2022-06-17 02:10:00,4280.0,4285.0,4280.0,4285.0,2100.0
2022-06-17 11:15:00+09:00,2022-06-17 02:15:00,4285.0,4285.0,4285.0,4285.0,500.0
2022-06-17 11:20:00+09:00,2022-06-17 02:20:00,4285.0,4290.0,4280.0,4285.0,5800.0
2022-06-17 11:25:00+09:00,2022-06-17 02:25:00,4285.0,4290.0,4285.0,4290.0,5100.0
2022-06-17 11:30:00+09:00,2022-06-17 02:30:00,4290.0,4290.0,4290.0,4290.0,200.0
2022-06-17 11:35:00+09:00,2022-06-17 02:35:00,NaN,NaN,NaN,NaN,NaN
2022-06-17 11:35:01+09:00,2022-06-17 02:35:01,4290.0,4290.0,4290.0,4290.0,0.0